# These are supported funding model platforms

buy_me_a_coffee: mohameddjaboux

custom:
  - https://buymeacoffee.com/mohameddjaboux
  - bitcoin:bc1q3smxjtjesh3km3rl0y89nyg964esdjkkmtwyhm
  - ethereum:0x891c40D9ac520DC6c8827eDD744ee15c472e88Ff
  - usdt:TRC20:TJriJCkKnG8d6dh1tejmz79JtUvnNoRirc
